version: '3'

services:
  mongo:
    image: mongo:4.4.3
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes: 
      - ${PWD}/home/data:/data/db
    tty: true
    networks: 
      - go-gin-recipes
  
  redis:
    image: redis:6.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes: 
      - ${PWD}/redis/conf:/usr/local/etc/redis
    tty: true
    networks: 
      - go-gin-recipes

networks: 
  go-gin-recipes:
    driver: bridge